/**
 * @typedef {import('./enums.js').SetEnum} SetEnum
 * @typedef {import('./enums.js').ModifierEnum} ModifierEnum
 * @typedef {import('./enums.js').SkillLineEnum} SkillLineEnum
 */

const SetEnum = Object.freeze({
  // Support sets with modifiers
  ROARING_OPPORTUNIST: 'SET_ROARING_OPPORTUNIST',
  SPELL_POWER_CURE: 'SET_SPELL_POWER_CURE',
  OLORIME: 'SET_OLORIME',
  SAXHLEEL_CHAMPION: 'SET_SAXHLEEL_CHAMPION',
  MASTER_ARCHITECT: 'SET_MASTER_ARCHITECT',
  WAR_MACHINE: 'SET_WAR_MACHINE',
  PEARLESCENT_WARD: 'SET_PEARLESCENT_WARD',
  POWERFUL_ASSAULT: 'SET_POWERFUL_ASSAULT',
  LORD_WARDEN_SET: 'SET_LORD_WARDEN_SET',

  // Player DPS sets
  SPRIGGAN: "SET_SPRIGGAN",
  SHATTERED_FATE: "SET_SHATTERED_FATE",
  ADVANCING_YOKEDA: "SET_ADVANCING_YOKEDA",
  SUL_XAN: "SET_SUL_XAN",
  MORAS_SCRIBE_THESIS: "SET_MORAS_SCRIBE_THESIS",
  ARMOR_SET_PEN_PASSIVE: "SET_ARMOR_SET_PEN_PASSIVE",
  ARENA_1_PIECE: "SET_ARENA_1_PIECE",
  WHORL_OF_THE_DEPTHS: "SET_WHORL_OF_THE_DEPTHS",
  TIDE_BORN_WILDSTALKER: "SET_TIDE_BORN_WILDSTALKER",
  ANSUULS_TORMENT: "SET_ANSUULS_TORMENT",

  // Mythics
  HARPOONER_KILT: "SET_HARPOONER_KILT",
  VELOTHI_UR_MAGE: "SET_VELOTHI_UR_MAGE",
  PEARLS_OF_EHLNOFEY: "SET_PEARLS_OF_EHLNOFEY",

  // Other support sets
  ELEMENTAL_CATALYST: "SET_ELEMENTAL_CATALYST",
  LUCENT_ECHOES: "SET_LUCENT_ECHOES",
  ALKOSH: "SET_ALKOSH",
  CRIMSON_OATH: "SET_CRIMSON_OATH",
  TREMORSCALE: "SET_TREMORSCALE",
  JORVULDS_GUIDANCE: "SET_JORVULDS_GUIDANCE",
  SYMPHONY_OF_BLADES: "SET_SYMPHONY_OF_BLADES_SET",
  OZEZAN_THE_INFERNO: "SET_OZEZAN_THE_INFERNO",
  ARCH_DRUID: "SET_ARCH_DRUID",
  TURNING_TIDE: "SET_TURNING_TIDE",
  YOLNAHKRIIN: "SET_YOLNAHKRIIN",
  PILLAGERS_PROFIT: "SET_PILLAGERS_PROFIT",
  NAZARAY: "SET_NAZARAY",
  BARON_ZAUDRUS: "SET_BARON_ZAUDRUS",

  // Not real sets, but indicators of sets with personal effects. Personal sets worn (e.g. 1-piece slimecraw, 4-piece Tideborn)
  PERSONAL_CRIT_SET: "SET_PERSONAL_CRIT_SET",
  PERSONAL_PEN_SET: "SET_PERSONAL_PEN_SET",
  PERSONAL_MISC_SET: "SET_PERSONAL_MISC_SET",
});

const SetTypeEnum = Object.freeze({
  PERSONAL_SET: "SET_TYPE_PERSONAL_SET",
  SUPPORT_SET: "SET_TYPE_SUPPORT_SET",
  MYTHIC_SET: "SET_TYPE_MYTHIC_SET",
  MONSTER_SET: "SET_TYPE_MONSTER_SET",
});

