const RacialPassiveEnum = Object.freeze({
  FELINE_AMBUSH: "RACIAL_PASSIVE_FELINE_AMBUSH",
  HUNTERS_EYE: "RACIAL_PASSIVE_HUNTERS_EYE",
});

const SkillTypeEnum = Object.freeze({
  // Non-class
  CLASS_SKILL: 'SKILL_TYPE_CLASS_SKILL',
  CLASS_PASSIVE: 'SKILL_TYPE_CLASS_PASSIVE',
  WEAPON_PASSIVE: 'SKILL_TYPE_WEAPON_PASSIVE',
  ARMOUR_PASSIVE: 'SKILL_TYPE_ARMOUR_PASSIVE',
});

const SkillEnum = Object.freeze({
  // Class Skills
  CRYSTAL_WEAPON: "SKILL_CRYSTAL_WEAPON",
  RUNIC_SUNDER: "SKILL_RUNIC_SUNDER",
  // Class Passives
  ADVANCED_SPECIES: "SKILL_ADVANCED_SPECIES",
  DISMEMBER: "SKILL_DISMEMBER",
  ENERGIZED: "SKILL_ENERGIZED",
  FATED_FORTUNE: "SKILL_FATED_FORTUNE",
  HEMORRHAGE: "SKILL_HEMORRHAGE",
  PIERCING_COLD: "SKILL_PIERCING_COLD",
  PIERCING_SPEAR: "SKILL_PIERCING_SPEAR",
  SPLINTERED_SECRETS: "SKILL_SPLINTERED_SECRETS",
  WORLD_IN_RUIN: "SKILL_WORLD_IN_RUIN",
  // Weapon Passives
  HEAVY_WEAPONS_AXE: "SKILL_HEAVY_WEAPONS_AXE",
  HEAVY_WEAPONS_MACE: "SKILL_HEAVY_WEAPONS_MACE",
  TWIN_BLADE_BLUNT_AXES: "SKILL_TWIN_BLADE_BLUNT_AXES",
  TWIN_BLADE_BLUNT_MACES: "SKILL_TWIN_BLADE_BLUNT_MACES",
  SHARPENED: "SKILL_SHARPENED",
  // Armor Passives
  CONCENTRATION: "SKILL_CONCENTRATION",
  DEXTERITY: "SKILL_DEXTERITY",
});

const SkillLineEnum = Object.freeze({
  // Non-class
  FIGHTERS_GUILD: 'SL_FIGHTERS_GUILD',
  MAGES_GUILD: 'SL_MAGES_GUILD',
  UNDAUNTED: 'SL_UNDAUNTED',
  THIEVES_GUILD: 'SL_THIEVES_GUILD',
  PSIJIC_ORDER: 'SL_PSIJIC_ORDER',
  DARK_BROTHERHOOD: 'SL_DARK_BROTHERHOOD',
  VAMPIRE: 'SL_VAMPIRE',
  WEREWOLF: 'SL_WEREWOLF',
  SOUL_MAGIC: 'SL_SOUL_MAGIC',
  ASSAULT: 'SL_ASSAULT',
  SUPPORT: 'SL_SUPPORT',

  // Arcanist
  HERALD_OF_THE_TOME: "SL_HERALD_OF_THE_TOME",
  SOLDIER_OF_APOCRYPHA: "SL_SOLDIER_OF_APOCRYPHA",
  CURATIVE_RUNEFORMS: "SL_CURATIVE_RUNEFORMS",
  // Dragonknight
  ARDENT_FLAME: "SL_ARDENT_FLAME",
  DRACONIC_POWER: "SL_DRACONIC_POWER",
  EARTHEN_HEART: "SL_EARTHEN_HEART",
  // Necromancer
  GRAVE_LORD: "SL_GRAVE_LORD",
  BONE_TYRANT: "SL_BONE_TYRANT",
  LIVING_DEATH: "SL_LIVING_DEATH",
  // Nightblade
  ASSASSINATION: "SL_ASSASSINATION",
  SHADOW: "SL_SHADOW",
  SIPHONING: "SL_SIPHONING",
  // Sorcerer
  DAEDRIC_SUMMONING: "SL_DAEDRIC_SUMMONING",
  DARK_MAGIC: "SL_DARK_MAGIC",
  STORM_CALLING: "SL_STORM_CALLING",
  // Templar
  AEDRIC_SPEAR: "SL_AEDRIC_SPEAR",
  DAWNS_WRATH: "SL_DAWNS_WRATH",
  RESTORING_LIGHT: "SL_RESTORING_LIGHT",
  // Warden
  ANIMAL_COMPANIONS: "SL_ANIMAL_COMPANIONS",
  GREEN_BALANCE: "SL_GREEN_BALANCE",
  WINTERS_EMBRACE: "SL_WINTERS_EMBRACE",
  // Weapons & Armor
  TWO_HANDED: "SL_TWO_HANDED",
  ONE_HAND_AND_SHIELD: "SL_ONE_HAND_AND_SHIELD",
  DUAL_WIELD: "SL_DUAL_WIELD",
  BOW: "SL_BOW",
  DESTRUCTION_STAFF: "SL_DESTRUCTION_STAFF",
  RESTORATION_STAFF: "SL_RESTORATION_STAFF",
  LIGHT_ARMOR: "SL_LIGHT_ARMOR",
  MEDIUM_ARMOR: "SL_MEDIUM_ARMOR",
  HEAVY_ARMOR: "SL_HEAVY_ARMOR",
});